# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "Jun Lei | 雷军"

# A description of your site for meta tag, search engine results.
description: "Xiaomi is a technology company in Beijing, China."

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://scriptor-jekyll.netlify.com"

# Favicon
favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /home.html
  - text: Research
    url: /research.html
  - text: Teaching
    url: /teaching.html
  - text: Xiaomi
    url: https://www.mi.com/index.html
  - text: Miscellaneous
    url: /miscellaneous.html
  - text: Permalink
    url: _pages/about.md

# The shortname for your Disqus site to enable comments.
disqus: xiaomi

# Colors
accent_color: '#2d72d9'

# Site footer
footer:
  content: "Jun Lei @ Xiaomi Corp."
  has_social: false

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
